name: PR checks

on:
  pull_request:
    branches: [main]

jobs:
  automated-checks:
    name: Automated checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Check types
        run: bun run typecheck

      - name: Run tests
        run: bun test
